---
version: 0.2

phases:
  pre_build:
    commands:
      - mvn dependency:go-offline
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - mvn deploy
cache:
  paths:
    - '/root/.m2/repository/**/*'
