---
version: 0.2

phases:
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - mvn deploy -P '!build-tutorial-steps' # don't try to deploy the tutorial
cache:
  paths:
    - '/root/.m2/repository/**/*'
