---
version: 0.2

phases:
  build:
    commands:
      - ./mvnw clean install
  post_build:
    commands:
      - ./.cicd/deploy-if-tagged.sh
cache:
  paths:
    - '/root/.m2/repository/**/*'
    - '/root/.m2/wrapper/**/*'
