complexity:
  LongMethod:
    excludes: "**/integrationtest/*Specs.kt"
  TooManyFunctions:
    active: false
style:
  MagicNumber:
    active: false
exceptions:
  TooGenericExceptionCaught:
    active: false
