baseurl: /kotlin-uapi/

defaults:
- scope:
    path: "" # an empty string here means all files in the project
  values:
    layout: "default"
- scope:
    path: ""
    type: "tutorial"
  values:
    layout: "tutorial"
- scope:
    path: ""
    type: "reference"
  values:
    layout: "collection"

theme: minima
title: University API - Kotlin

collections_dir: content

collections:
  tutorial:
    output: true
    order: 1
  reference:
    output: true
    order: 2

plugins:
- jekyll-relative-links

relative_links:
  enabled:     true
  collections: true
